
#DATASOURCE 2
spring.application.name=ejercicio_supermecado
spring.datasource.url=jdbc:h2:mem:superdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=

#JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Comportamiento de MySQL en TEST 
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#H2 en consola 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always